# Plone settings

# THIS STUFF YOU CAN CHANGE
plone_target_path: "/usr/local/Plone"
plone_var_path: "/var/local/Plone"
plone_instance_name: baobab
plone_initial_password: 123qwe

# DO NOT TOUCH THE STUFF BELOW HERE
plone_version: '4.3.11'
plone_python_version: '2.7'
plone_install_zeoserver: yes
plone_backup_path: no
plone_create_site: no
plone_buildout_cache_url: https://launchpad.net/plone/{{ plone_major_version }}/4.3.18/+download/buildout-cache.tar.bz2
plone_additional_eggs:
  - bika.lims
  - baobab.lims
  - graphite.theme
plone_buildout_extra: |
  develop =
    src/bika.lims
    src/baobab.lims
    src/graphite.theme
plone_client_base_port: 8080
