---
sudo: required
dist: xenial

language: python
python: "2.7"

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo pip install --upgrade pip

install:
  - pip install ansible
  - pip install ansible-lint

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv
  - curl 127.0.0.1:80 | grep -i baobab
