version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    working_directory: ~/baobab-ansible

    steps:
      - run:
          name: Install System Packages
          command: curl https://bootstrap.pypa.io/get-pip.py | python && pip install ansible

      - checkout